name: 1_First job

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: enter enbvironment vale

      space:
        type: string
        required: true
        description: enter space value



jobs:
  build:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      env_var_a : "abc"
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_BASE_DIR: ${{ secrets.GH_BASE_DIR }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: List of Dependencies after installing python
        run: | 
          pip list
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run : |
          pip install -e ".[dev]"
      - name: List installedDependencies
        run: |
          pip list
      - name: List installedDependencies With Their Installed Path
        run: |
          pip list -v
      - name: List installedDependencies With Their Installed Path For NewLibs
        run: |
          echo `pip list -v | grep -i "python-generic-function"`
      - name: Run Unit tests
        run: |
          pytest me/personal --cov
      - name: List environment Variables
        run: |
          python ./me/personal/perform_calc/run_env_vars.py
  run:
    needs: build
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      env_var_b : "def"
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_BASE_DIR: ${{ vars.GH_BASE_DIR }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      - name: List installedDependencies With Their Installed Path
        run: |
          pip list -v
      - name: runcode
        run: |
          python ./me/personal/perform_calc/run_code.py
          python ./me/personal/perform_calc/run_code_two.py
          python ./me/personal/perform_calc/run_code_env.py
          python ./me/personal/perform_calc/run_code_env_two.py
          



